services:
  - type: web
    name: candlestick-screener
    env: python
    runtime: python-3.11.9
    region: oregon
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app:app --host 0.0.0.0 --port $PORT --workers 1
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DUCKDB_PATH
        sync: false
      - key: ALPHA_VANTAGE_API_KEY
        sync: false
